weather_api_key: e141e04e4a545534c60d92a7c8291b99

cities:
  - name: Bengaluru
    lat: 12.9716
    lon: 77.5946
  - name: Mumbai
    lat: 19.0760
    lon: 72.8777
  - name: Delhi
    lat: 28.6139
    lon: 77.2090
  - name: Chennai
    lat: 13.0827
    lon: 80.2707
  - name: Hyderabad
    lat: 17.3850
    lon: 78.4867
  - name: Kolkata
    lat: 22.5726
    lon: 88.3639
  - name: Pune
    lat: 18.5204
    lon: 73.8567

project_id: urban-mobility-aqi
bq_dataset: mobility_ds
bq_table: fact_mobility
mssql_conn: DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;DATABASE=mobility_dw;Trusted_Connection=yes;
